apiVersion: v1
kind: Service
metadata:
  name: ai-hedge-fund
  namespace: ai-hedge-fund
  labels:
    app: ai-hedge-fund
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    app: ai-hedge-fund
