replicaCount: 1

image:
  repository: "localhost/ai-hedge-fund"
  tag: "v1.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8501

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

nodeSelector:
  kubernetes.io/hostname: mgplcb05
